FROM golang:1-alpine3.18

RUN apk add --no-cache git ca-certificates build-base su-exec olm-dev bash jq yq curl

COPY . /build
WORKDIR /build
ARG DBG=0
if [ "$DBG" = 1 ]; then
    go install github.com/go-delve/delve/cmd/dlv@latest
else
    touch /go/bin/dlv
fi
RUN ./build.sh -o /mautrix-whatsapp

# Setup development stack using gow
RUN go install github.com/mitranim/gow@latest
RUN echo 'gow run /build $@' > /usr/bin/mautrix-whatsapp \
    && chmod +x /usr/bin/mautrix-whatsapp
VOLUME /data
